# install.packages('raster', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('rgdal', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('rgeos', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('maptools', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('shapefiles', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('ncdf4', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('terra', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('rworldmap', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('spatstat.geom', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('ggmap', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('rgee', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('plotKML', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('leaflet', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('dismo', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('geodata', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)

# install.packages('Hmisc', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('circlize', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('diagis', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('ggnewscale', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('lmerTest', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('lme4', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('metafor', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('metan', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('pbapply', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('FactoMineR', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('doParallel', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('ggpubr', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('broom', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('mlr3', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('RInside', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('doSNOW', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('rdrop2', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('Microsoft365R', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('googleCloudStorageR', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('circular', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('miceadds', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('multimode', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('sfsmisc', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('rJava', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('R.utils', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('reshape2', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('rworldxtra', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('RCurl', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('tidyverse', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('ranger', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('sodium', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)

# install.packages('pals', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('ggcorrplot', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('aws.s3', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('agricolae', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('xlsx', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('ecmwfr', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('envirem', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('maps', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
# install.packages('dplyr', dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 8)
install.packages(c('raster', 'rgdal', 'rgeos', 'maptools', 'shapefiles', 'ncdf4', 'terra', 'rworldmap', 'spatstat.geom', 'ggmap', 'rgee', 'plotKML', 'leaflet', 'dismo', 'geodata', 'Hmisc', 'circlize', 'diagis', 'ggnewscale', 'lmerTest', 'lme4', 'metafor', 'metan', 'pbapply', 'FactoMineR', 'doParallel', 'ggpubr', 'broom', 'mlr3', 'RInside',  'doSNOW', 'rdrop2', 'Microsoft365R', 'googleCloudStorageR', 'circular', 'miceadds', 'multimode', 'sfsmisc', 'rJava', 'R.utils', 'reshape2', 'rworldxtra', 'RCurl', 'tidyverse', 'ranger', 'sodium', 'pals', 'ggcorrplot', 'aws.s3', 'agricolae', 'xlsx', 'ecmwfr', 'envirem', 'maps', 'dplyr'), dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus = 4)

devtools::install_github(c("CIAT-DAPA/analogues",
                   "SantanderMetGroup/loadeR.java",
                   "SantanderMetGroup/climate4R.UDG",
                   "SantanderMetGroup/loadeR",
                   "SantanderMetGroup/transformeR",
                   "SantanderMetGroup/visualizeR",
                   "SantanderMetGroup/downscaleR",
                   "femiguez/apsimx"), configure.args="Ncpus = 4")
devtools::install_github(c("SantanderMetGroup/convertR",
                   "SantanderMetGroup/climate4R.indices"))
